workflows:
  android-workflow:
    name: Android Debug Build
    max_build_duration: 60
    environment:
      java: 17
      android:
        api_level: 34
        build_tools_version: 34.0.0
    scripts:
      - name: Ensure executable
        script: chmod +x ./gradlew || true
      - name: Clean
        script: ./gradlew clean
      - name: Assemble debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
